# Generated by Django 5.2.5 on 2025-08-11 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='цена в центах, не меньше 50', validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
